---
dependencies: []

galaxy_info:
  author: cecepm
  description: Configure system-wide locale
  license: "license (BSD, MIT)"
  min_ansible_version: 1.6
  platforms:
  - name: Ubuntu
    versions:
    - all
  categories:
  - system
