---
- name: Download latest anaconda installer
  sudo: False
  get_url: url=https://3230d63b5fc54e62148e-c95ac804525aac4b6dba79b00b39d1d3.ssl.cf1.rackcdn.com/Anaconda-2.2.0-Linux-x86_64.sh 
           dest=/tmp/anaconda.sh

- name: Install anaconda (default folder)
  sudo: false
  shell: bash /tmp/anaconda.sh -b

- name: Add anaconda to the PATH
  lineinfile: dest=/home/{{ ansible_ssh_user }}/.bashrc line="export PATH=/home/{{ ansible_ssh_user }}/anaconda/bin:$PATH"

- name: Restart instance
  command: shutdown -r now "Ansible reboot triggered"  
  async: 0 
  poll: 0 
  ignore_errors: true

- name: Wait for instance to restart
  local_action: wait_for host={{ ansible_ssh_host }} state=started port=22 delay=1 timeout=300
  sudo: False

- name: Update conda to latest version
  sudo: False
  command: /home/{{ ansible_ssh_user }}/anaconda/bin/conda update conda --yes -q

- name: Install pip
  sudo: False
  command: /home/{{ ansible_ssh_user }}/anaconda/bin/conda install pip --yes -q
