---
- name: Download miniconda installer
  get_url: url={{ miniconda_installer }}
           dest=/tmp/miniconda.sh

- name: Check if miniconda is installed
  stat:
    path: ~/miniconda
  register: installed
  become: false

- name: Install miniconda (default folder)
  shell: bash /tmp/miniconda.sh -b -p $HOME/miniconda
  become: false
  when: installed.stat.exists == False

- name: Add miniconda to the PATH
  lineinfile: dest=~/.bashrc line="export PATH=~/miniconda/bin:$PATH"
  become: false
  when: installed.stat.exists == False

- name: Update conda 
  shell: ~/miniconda/bin/conda update conda -y --force
  become: false

- name: Check if anaconda35 env is installed
  stat:
    path: ~/miniconda/envs/anaconda35
  register: anaconda35
  become: false

- name: Create anaconda python 3.5 env
  shell: ~/miniconda/bin/conda create -y -n anaconda35 python=3.5 anaconda
  become: false
  when: anaconda35.stat.exists == False

- name: Upgrating setuptools
  shell: /usr/bin/yes | ~/miniconda/envs/anaconda35/bin/pip install -q --upgrade setuptools
  ignore_errors: yes
  become: false
  when: anaconda35.stat.exists == False

- name: By default activate anaconda35 env
  lineinfile: dest=~/.bashrc line="source activate anaconda35"
  become: false
  when: anaconda35.stat.exists == False

- name: Check if anaconda27 env is installed
  stat:
    path: ~/miniconda/envs/anaconda27
  register: anaconda27
  become: false

- name: Create anaconda python 2.7 env
  shell: ~/miniconda/bin/conda create -y -n anaconda27 python=2.7 anaconda
  become: false
  when: anaconda27.stat.exists == False



