---
- name: Install caffe2 dependencies
  apt: 
    pkg: '{{ caffe2_dependencies }}'
    state: installed
    update_cache: yes
    install_recommends: no

- name: Cloning caffe2 git repo
  git: repo=https://github.com/caffe2/caffe2.git dest=~/caffe2
  become: false

- name: Install python dependencies
  shell: ~/miniconda/envs/anaconda27/bin/pip install {{ item }}
  with_items:
    - protobuf
    - pydot python-nvd3
    - graphviz
    - hypothesis
  become: false

- name: Symlink anaconda27
  file: 
    src: /home/ubuntu/miniconda/envs/anaconda27/bin/python
    dest: /usr/bin/python 
    state: link

- name: Build caffe
  shell: make -j$(nproc) chdir=~/caffe2/
  become: false

- name: Install caffe2
  shell: make install chdir=~/caffe2/build/

- name: reverting symlink
  file: 
    src: /usr/bin/python2.7
    dest: /usr/bin/python 
    state: link

