---
- name: checkout keras repo
  git: repo=https://github.com/fchollet/keras.git dest=~/keras update=yes
  become: false

- name: Install latest version of keras
  shell: ~/miniconda/envs/anaconda35/bin/pip install --upgrade -e ~/keras
  become: false