---
- name: Checkout MXNet repo
  git: repo=https://github.com/dmlc/mxnet.git dest=~/mxnet update=yes
  become: false

- name: Copy config.mk
  shell: cp ~/mxnet/make/config.mk ~/mxnet
  become: false

- name: Update config.mk
  blockinfile:
    dest: ~/mxnet/config.mk
    block: |
      USE_CUDA=1
      USE_CUDA_PATH=/usr/local/cuda
      USE_CUDNN=1
  become: false

- name: Ensure MXNet dependencies are installed
  apt: name={{ item }} state=installed
  with_items:
    - build-essential
    - libatlas-base-dev
    - libopencv-dev
    - graphviz

- name: Make MXNet
  shell: make -j$(nproc) chdir=~/mxnet/
  become: false

- name: Install graphviz
  shell: ~/anaconda2/bin/pip install --upgrade graphviz
  become: false

- name: Install MXNet python package
  shell: ~/anaconda2/bin/python setup.py install chdir=~/mxnet/python
  become: false