---
- name: Install latest version of theanorc
  shell: ~/miniconda/envs/anaconda35/bin/pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git
  become: false

- name: Copy theanorc file to instance
  copy: src=theanorc dest=~/.theanorc
  become: false