deeplearning_dependencies:
- libopenblas-dev
- libprotobuf-dev
- libleveldb-dev
- libsnappy-dev
- libopencv-dev
- libboost-all-dev
- libhdf5-serial-dev
- libgflags-dev
- libgoogle-glog-dev
- liblmdb-dev
- protobuf-compiler

caffe_dependencies:
- leveldb
- protobuf
- python-gflags