
miniconda_installer: https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh

caffe2_dependencies:
- libgoogle-glog-dev
- libprotobuf-dev
- protobuf-compiler
- libgtest-dev
- libiomp-dev
- libleveldb-dev
- liblmdb-dev
- libopencv-dev
- libopenmpi-dev
- libsnappy-dev
- openmpi-bin
- openmpi-doc
- python-pydot