
anaconda_installer: https://repo.continuum.io/archive/Anaconda2-4.3.1-Linux-x86_64.sh

caffe_dependencies:
- libopenblas-dev
- libprotobuf-dev
- libleveldb-dev
- libsnappy-dev
- libopencv-dev
- libboost-all-dev
- libhdf5-serial-dev
- libgflags-dev
- libgoogle-glog-dev
- liblmdb-dev
- protobuf-compiler

caffe2_dependencies:
- libgtest-dev
- libiomp-dev     
- libleveldb-dev
- liblmdb-dev
- libopencv-dev
- libopenmpi-dev
- libsnappy-dev
- openmpi-bin
- openmpi-doc
- python-pydot
