---
- name: Download latest CUDA drivers
  get_url: url=http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/cuda-repo-ubuntu1404_7.0-28_amd64.deb dest=/tmp/cuda.deb

- name: Add CUDA deb
  shell: dpkg -i /tmp/cuda.deb

- name: Update packages
  shell: apt-get update

- name: Install cuda package
  shell: apt-get install -y cuda

- name: Adding cuda bin to PATH
  lineinfile: dest=/home/{{ ansible_ssh_user }}/.bashrc line="export PATH=$PATH:/usr/local/cuda/bin"

- name: Adding cuda lib64 to LD_LIBRARY_PATH
  lineinfile: dest=/home/{{ ansible_ssh_user }}/.bashrc line="export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64"

- name: Adding cuda root to CUDA_ROOT
  lineinfile: dest=/home/{{ ansible_ssh_user }}/.bashrc line="export CUDA_ROOT=/usr/local/cuda"

- name: Restart instance
  command: shutdown -r now "Ansible reboot triggered"  
  async: 0 
  poll: 0 
  ignore_errors: true

- name: Wait for instance to restart
  local_action: wait_for host={{ ansible_ssh_host }} state=started port=22 delay=1 timeout=300
  sudo: False