---
- name: Download latest CUDA drivers
  get_url: url=http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/cuda-repo-ubuntu1404_7.5-18_amd64.deb dest=/tmp/cuda.deb

- name: Add CUDA deb
  shell: dpkg -i /tmp/cuda.deb

- name: Update packages
  apt: update_cache=yes

- name: Install cuda package
  apt: name=cuda state=present

- name: Adding cuda bin to PATH
  lineinfile: dest=~/.bashrc line="export PATH=$PATH:/usr/local/cuda/bin"
  become: false

- name: Adding cuda lib64 to LD_LIBRARY_PATH
  lineinfile: dest=~/.bashrc line="export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64"
  become: false

- name: Adding cuda root to CUDA_ROOT
  lineinfile: dest=~/.bashrc line="export CUDA_ROOT=/usr/local/cuda"
  become: false

- name: Restart server
  command: /sbin/reboot
  async: 0
  poll: 0
  ignore_errors: true

- name: Wait for server to restart
  local_action:
    module: wait_for host={{ inventory_hostname }} delay=30 timeout=120 state=started
  become: false
