---
- name: Add java8 apt-repository
  apt_repository: repo='ppa:webupd8team/java'
  tags:
    - java8

- name: Automatically select the Oracle License
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  tags:
    - java8

- name: Install java8
  apt: pkg=oracle-java8-installer state=latest update_cache=yes force=yes
  tags:
    - java8