---
- apt: upgrade=dist update_cache=yes

- name: Install linux packages
  apt: pkg={{ linux_packages }} state=installed update_cache=yes

- name: Restart server
  command: /sbin/reboot
  async: 0
  poll: 0
  ignore_errors: true

- name: Wait for server to restart
  local_action:
    module: wait_for host={{ inventory_hostname }} delay=30 timeout=120 state=started
  become: false