---
- name: Ensure locales is installed
  apt: name=locales state=installed

- name: Ensure language packages are installed
  apt: pkg={{ locale_language_packs }} state=installed
  register: locale_languages

- name: Ensure dpkg is reconfigured
  command: dpkg-reconfigure locales
  when: locale_languages.changed

- name: Set system wide locale
  template: >
    src=locale.j2
    dest=/etc/default/locale
    owner=root group=root mode=644

- name: Detect locale gen file
  stat:
    path: /etc/local.gen
  register: locales_gen

- name: Create locale gen file
  file:
    path: /etc/local.gen
    state: touch
  when: not locales_gen.stat.exists

- name: Detect locale supported file
  stat:
    path: /var/lib/locales/supported.d/local
  register: locales_supported

- name: Create locale supported file
  file:
    path: /var/lib/locales/supported.d/local
    state: touch
  when: not locales_supported.stat.exists

- name: Ensure locales is generated
  locale_gen: name={{ locale_settings.LANG }} state=present
