---
- name: Ensure tzdata is installed
  apt: name=tzdata state=installed

- name: Set to correct timezone
  file: >
    src=/usr/share/zoneinfo/{{ ntp_timezone }}
    dest=/etc/localtime
    state=link
    force=true

- name: Ensure ntp packages is installed
  apt: name={{ item }} state=installed
  with_items:
  - ntp
  - ntpdate

- name: Ensure service ntp is running and enabled
  service: name=ntp state=started enabled=yes
